apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: document-status-service
requires:
  - path: ../../common
    configs: [common]
build:
  tagPolicy:
    gitCommit: {}
  local:
    concurrency: 0
  artifacts:
  - image: document-status-service
    requires:
      - image: common
        alias: BASE_IMG
    sync:
      infer:
        - '**/*.py'
        - '**/*.json'
portForward:
- resourceType: service
  resourceName: document-status-service
  port: 80
  localPort: 8894
deploy:
  kustomize:
    paths:
    - ./kustomize/minikube
profiles:
- name: custom
  build:
    googleCloudBuild: {}
    artifacts:
    - image: document-status-service
      requires:
      - image: common
        alias: BASE_IMG
  deploy:
    kustomize:
      paths:
      - ./kustomize/custom
- name: prod_non_cloudbuild
  deploy:
    kustomize:
      paths:
      - ./kustomize/prod
- name: prod
  deploy:
    kustomize:
      paths:
      - ./kustomize/prod
  build:
    googleCloudBuild: {}
    artifacts:
    - image: document-status-service
      docker:
        cacheFrom:
          - document-status-service
          - document-status-service:latest
      requires:
      - image: common
        alias: BASE_IMG
- name: dev
  build:
    googleCloudBuild: {}
    artifacts:
    - image: document-status-service
      docker:
        cacheFrom:
          - document-status-service
          - document-status-service:latest
      requires:
        - image: common
          alias: BASE_IMG
      sync:
        infer:
          - '**/*.py'
          - '**/*.json'
  deploy:
    kustomize:
      paths:
      - ./kustomize/dev