apiVersion: v1
kind: Service
metadata:
  name: hitl-service
  labels:
    app: hitl-service
spec:
  type: LoadBalancer
  loadBalancerIP: 35.238.35.3
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hitl-service
