# Master Skaffold
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: backends
requires:
- path: ./common
  configs: [common]
  activeProfiles: &dev_and_custom_backends
  - name: custom
    activatedBy: [custom]
  - name: dev
    activatedBy: [dev]

- path: ./microservices/sample_service
  configs: [sample-service]
  activeProfiles:  *dev_and_custom_backends


- path: ./microservices/upload_service
  configs: [upload-service]
  activeProfiles:  *dev_and_custom_backends

- path: ./microservices/classification_service
  configs: [classification-service]
  activeProfiles:  *dev_and_custom_backends

- path: ./microservices/extraction_service
  configs: [ extraction-service ]
  activeProfiles: *dev_and_custom_backends

- path: ./microservices/validation_service
  configs: [validation-service]
  activeProfiles:  *dev_and_custom_backends

- path: ./microservices/hitl_service
  configs: [hitl-service]
  activeProfiles:  *dev_and_custom_backends

profiles:
- name: custom
- name: dev
  activation:
  - kubeContext: gke_claims-processing-dev_us-central1_default-cluster
