apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: matching-service
requires:
  - path: ../../common
    configs: [common]
build:
  tagPolicy:
    gitCommit: {}
  local:
    concurrency: 0
  artifacts:
  - image: matching-service
    requires:
      - image: common
        alias: BASE_IMG
    sync:
      infer:
        - '**/*.py'
        - '**/*.json'
portForward:
- resourceType: service
  resourceName: matching-service
  port: 80
  localPort: 8895
deploy:
  kustomize:
    paths:
    - ./kustomize/minikube
profiles:
- name: custom
  build:
    googleCloudBuild: {}
    artifacts:
    - image: matching-service
      requires:
      - image: common
        alias: BASE_IMG
  deploy:
    kustomize:
      paths:
      - ./kustomize/custom
- name: prod_non_cloudbuild
  deploy:
    kustomize:
      paths:
      - ./kustomize/prod
- name: prod
  deploy:
    kustomize:
      paths:
      - ./kustomize/prod
  build:
    googleCloudBuild: {}
    artifacts:
    - image: matching-service
      docker:
        cacheFrom:
          - matching-service
          - matching-service:latest
      requires:
      - image: common
        alias: BASE_IMG
- name: dev
  activation:
  - kubeContext: gke_claims-processing-dev_us-central1_default-cluster
  build:
    googleCloudBuild: {}
    artifacts:
    - image: gcr.io/claims-processing-dev/matching-service
      docker:
        cacheFrom:
          - gcr.io/claims-processing-dev/matching-service
          - gcr.io/claims-processing-dev/matching-service:latest
      requires:
        - image: gcr.io/claims-processing-dev/common
          alias: BASE_IMG
      sync:
        infer:
          - '**/*.py'
          - '**/*.json'
  deploy:
    kustomize:
      paths:
      - ./kustomize/dev