apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: adp-ui
build:
  googleCloudBuild: {}
  artifacts:
  - image: adp-ui
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - ./kustomize/dev
profiles:
- name: prod
  deploy:
    kustomize:
      paths:
      - ./kustomize/prod
  build:
    googleCloudBuild: {}
    artifacts:
    - image: adp-ui
- name: dev
  build:
    googleCloudBuild: {}
    artifacts:
    - image: adp-ui
      sync:
        infer:
          - '**/*.js'
          - '**/*.json'
          - '**/*.css'
      docker:
        dockerfile: Dockerfile-dev
  deploy:
    kustomize:
      paths:
      - ./kustomize/dev