apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: common
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: common
    sync:
      infer:
        - '**/*.py'
        - '**/*.json'

profiles:
- name: custom
  build:
    googleCloudBuild: {}
    artifacts:
    - image: common
      docker:
        cacheFrom:
          - common
          - common:latest
- name: prod
  build:
    googleCloudBuild: {}
    artifacts:
    - image: common
      docker:
        cacheFrom:
          - common
          - common:latest
      sync:
        infer:
          - '**/*.py'
          - '**/*.json'
- name: dev
  activation:
  - kubeContext: gke_claims-processing-dev_us-central1_default-cluster
  build:
    googleCloudBuild: {}
    artifacts:
    - image: gcr.io/claims-processing-dev/common
      docker:
        cacheFrom:
          - gcr.io/claims-processing-dev/common
          - gcr.io/claims-processing-dev/common:latest
      sync:
        infer:
          - '**/*.py'
          - '**/*.json'