apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-status-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: document-status-service
        image: gcr.io/claims-processing-dev/document-status-service
        imagePullPolicy: Always
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: PROJECT_ID
        - name: EXTERNAL_DATA_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: EXTERNAL_DATA_PROJECT_ID
        - name: DATABASE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: DATABASE_PREFIX