apiVersion: v1
kind: Service
metadata:
  name: classification-service
  labels:
    app: classification-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: classification-service
