apiVersion: v1
kind: Service
metadata:
  name: upload-service
  labels:
    app: upload-service
spec:
  type: NodePort
  ports:
  - port: 8889
    protocol: TCP
    targetPort: 8889
  selector:
    app: upload-service
