
apiVersion: v1
kind: Service
metadata:
  name: upload-service
  labels:
    app: upload-service
spec:
  type: LoadBalancer
  loadBalancerIP: 34.66.3.198
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: upload-service
