apiVersion: v1
kind: Service
metadata:
  name: matching-service
  labels:
    app: matching-service
spec:
  type: LoadBalancer
  loadBalancerIP: 35.224.90.131
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: matching-service
