apiVersion: v1
kind: Service
metadata:
  name: extraction-service
  labels:
    app: extraction-service
spec:
  type: LoadBalancer
  loadBalancerIP: 35.184.79.135
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: extraction-service
